name: json_dynamic_widget_plugin_ionicons
description: A plugin to the JSON Dynamic Widget to provide String name support for ionicons
homepage: https://github.com/peiffer-innovations/json_dynamic_widget_plugin_ionicons

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

analyzer:
  exclude: [lib/generated/**]

dependencies:
  child_builder: ^2.0.0
  flutter:
    sdk: flutter
  ionicons_named: ^1.0.0
  json_class: ^2.1.2+1
  json_dynamic_widget: ^3.6.0
  json_theme: ^3.2.3+1
  logging: ^1.0.2
  meta: ^1.7.0
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
