name: 'json_dynamic_widget_plugin_ionicons'
description: 'A plugin to the JSON Dynamic Widget to provide String name support for ionicons'
homepage: 'https://github.com/peiffer-innovations/json_dynamic_widget_plugin_ionicons'
version: '4.0.0+6'

environment: 
  sdk: '>=3.0.0 <4.0.0'

analyzer: 
  exclude: 
    - 'lib/generated/**'
    - 'lib/**/*.g.dart'


dependencies: 
  child_builder: '^2.0.1'
  flutter: 
    sdk: 'flutter'
  ionicons_named: '^1.3.1'
  json_class: '^3.0.0+6'
  json_dynamic_widget: '^7.0.3'
  json_theme: '^6.3.0'
  logging: '^1.2.0'
  meta: '^1.9.1'
  uuid: '^4.1.0'

false_secrets: 
  - 'example/web/index.html'

dev_dependencies: 
  build_runner: '^2.4.6'
  flutter_lints: '^3.0.0'
  flutter_test: 
    sdk: 'flutter'
  json_dynamic_widget_codegen: '^1.0.2'

ignore_updates: 
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
